"""
Medical Report Writer - Core Module

AI-powered clinical report generation including discharge summaries,
referral letters, consultation notes, operative reports, progress notes,
and transfer summaries.

⚠️ MEDICAL DISCLAIMER: All generated reports MUST be reviewed, verified,
and approved by a licensed physician before use in any clinical context.
This tool is an AI drafting assistant — NOT a replacement for clinical judgment.
"""

from typing import Optional, List, Dict, Any
import os
import sys
import logging
from datetime import datetime

# ---------------------------------------------------------------------------
# Path setup for shared common module
# ---------------------------------------------------------------------------
_common_path = os.path.join(os.path.dirname(__file__), '..', '..', '..')
sys.path.insert(0, os.path.abspath(_common_path))

from common.llm_client import chat, check_ollama_running  # noqa: E402

from .config import load_config, setup_logging  # noqa: E402

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logger = logging.getLogger("medical_report_writer")

CONFIG = load_config()
setup_logging(CONFIG.get("log_level", "INFO"))

# ---------------------------------------------------------------------------
# Medical disclaimer
# ---------------------------------------------------------------------------

DISCLAIMER = """
⚠️  PHYSICIAN REVIEW REQUIRED  ⚠️
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
All reports generated by this tool are AI-drafted documents that MUST be
reviewed, verified, and approved by a licensed physician before clinical use.

• This tool is a DRAFTING ASSISTANT — NOT a replacement for clinical judgment.
• Generated reports may contain inaccuracies or omissions.
• The treating physician is solely responsible for the final report content.
• Do NOT use AI-generated reports without thorough physician review.
• All patient data is processed LOCALLY — no data leaves this machine (HIPAA-friendly).

By using this tool, you acknowledge that all generated content requires
physician review and approval before any clinical application.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are a medical report writing assistant designed to help physicians draft clinical documents.

IMPORTANT RULES:
1. You generate DRAFT reports that MUST be reviewed and approved by a physician.
2. Use professional medical terminology and standard report formatting.
3. Include all relevant sections based on the report type.
4. Maintain a formal, objective clinical tone throughout.
5. Flag any areas where clinical data appears incomplete with [PHYSICIAN TO VERIFY].
6. Never fabricate clinical findings — only use provided data.
7. Include appropriate headers, dates, and structural elements.
8. Follow standard medical documentation practices (SOAP notes, etc.).

When generating reports:
- Structure the document with clear sections and headings.
- Use concise, precise medical language.
- Include all standard sections for the given report type.
- Mark any assumptions or gaps clearly for physician review.
- End with a note that the report requires physician review and signature.

Always include a footer: "This report was AI-drafted and requires physician review and approval." """

# ---------------------------------------------------------------------------
# Report types
# ---------------------------------------------------------------------------

REPORT_TYPES: Dict[str, Dict[str, str]] = {
    "discharge_summary": {
        "name": "Discharge Summary",
        "description": "Comprehensive summary of a patient's hospital stay, treatment, and discharge plan.",
        "sections": "Admission Date, Discharge Date, Admitting Diagnosis, Principal Diagnosis, "
                     "Hospital Course, Procedures, Discharge Medications, Follow-up Instructions",
    },
    "referral_letter": {
        "name": "Referral Letter",
        "description": "Letter referring a patient to a specialist or another healthcare provider.",
        "sections": "Patient Information, Reason for Referral, Clinical History, "
                     "Current Medications, Relevant Findings, Urgency Level",
    },
    "consultation_note": {
        "name": "Consultation Note",
        "description": "Documentation of a specialist consultation including findings and recommendations.",
        "sections": "Reason for Consultation, History of Present Illness, Review of Systems, "
                     "Physical Examination, Assessment, Recommendations",
    },
    "operative_report": {
        "name": "Operative Report",
        "description": "Detailed report of a surgical procedure including findings and technique.",
        "sections": "Preoperative Diagnosis, Postoperative Diagnosis, Procedure Performed, "
                     "Surgeon, Anesthesia, Findings, Technique, Estimated Blood Loss, Complications",
    },
    "progress_note": {
        "name": "Progress Note",
        "description": "Daily or periodic update on a patient's condition and treatment plan.",
        "sections": "Subjective, Objective, Assessment, Plan (SOAP format)",
    },
    "transfer_summary": {
        "name": "Transfer Summary",
        "description": "Summary document for transferring patient care to another facility.",
        "sections": "Patient Demographics, Transfer Reason, Current Diagnosis, Treatment Summary, "
                     "Current Medications, Pending Results, Receiving Facility",
    },
}


# ---------------------------------------------------------------------------
# Report generation functions
# ---------------------------------------------------------------------------

def generate_report(
    clinical_data: str,
    report_type: str = "progress_note",
    patient_demographics: Optional[str] = None,
    conversation_history: Optional[List[Dict[str, str]]] = None,
) -> str:
    """Generate a medical report using the LLM.

    Args:
        clinical_data: Free-text clinical data to include in the report.
        report_type: One of the keys in REPORT_TYPES.
        patient_demographics: Optional patient demographic information.
        conversation_history: Optional prior messages for multi-turn context.

    Returns:
        AI-drafted report text.

    Raises:
        ValueError: If report_type is not recognized.
        ConnectionError: If Ollama is not reachable.
    """
    if report_type not in REPORT_TYPES:
        raise ValueError(
            f"Unknown report type '{report_type}'. "
            f"Valid types: {', '.join(REPORT_TYPES.keys())}"
        )

    if conversation_history is None:
        conversation_history = []

    report_info = REPORT_TYPES[report_type]

    prompt_parts = [
        f"Generate a {report_info['name']} based on the following clinical data.",
        f"\nExpected sections: {report_info['sections']}",
    ]

    if patient_demographics:
        prompt_parts.append(f"\nPatient Demographics:\n{patient_demographics}")

    prompt_parts.append(f"\nClinical Data:\n{clinical_data}")
    prompt_parts.append(
        "\nPlease generate a complete, professionally formatted report. "
        "Mark any areas needing physician verification with [PHYSICIAN TO VERIFY]."
    )

    user_message = "\n".join(prompt_parts)

    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages.extend(conversation_history)
    messages.append({"role": "user", "content": user_message})

    logger.info(
        "Generating %s (%d prior messages)",
        report_info["name"], len(conversation_history),
    )

    try:
        response = chat(messages)
        logger.info("Generated report (%d chars)", len(response))
        return response
    except Exception as exc:
        logger.error("Report generation failed: %s", exc)
        raise


def generate_discharge_summary(
    admission_data: str,
    hospital_course: str,
    discharge_info: str,
) -> str:
    """Generate a discharge summary from structured admission data.

    Args:
        admission_data: Admission details (date, diagnosis, presenting complaints).
        hospital_course: Description of hospital stay, treatments, procedures.
        discharge_info: Discharge medications, follow-up, instructions.

    Returns:
        AI-drafted discharge summary.
    """
    clinical_data = (
        f"ADMISSION DATA:\n{admission_data}\n\n"
        f"HOSPITAL COURSE:\n{hospital_course}\n\n"
        f"DISCHARGE INFORMATION:\n{discharge_info}"
    )

    return generate_report(clinical_data, report_type="discharge_summary")


def generate_referral_letter(
    patient_info: str,
    reason: str,
    clinical_findings: str,
    requesting_physician: Optional[str] = None,
) -> str:
    """Generate a referral letter to a specialist.

    Args:
        patient_info: Patient demographics and relevant history.
        reason: Reason for referral.
        clinical_findings: Relevant clinical findings and test results.
        requesting_physician: Name of the referring physician.

    Returns:
        AI-drafted referral letter.
    """
    parts = [
        f"PATIENT INFORMATION:\n{patient_info}",
        f"\nREASON FOR REFERRAL:\n{reason}",
        f"\nCLINICAL FINDINGS:\n{clinical_findings}",
    ]

    if requesting_physician:
        parts.append(f"\nREFERRING PHYSICIAN: {requesting_physician}")

    clinical_data = "\n".join(parts)
    return generate_report(clinical_data, report_type="referral_letter")


def format_report(raw_report: str, formatting_style: str = "standard") -> str:
    """Format a raw report according to the specified style.

    Args:
        raw_report: The raw report text to format.
        formatting_style: One of 'standard', 'compact', 'detailed'.

    Returns:
        Formatted report text.
    """
    if not raw_report or not raw_report.strip():
        return raw_report

    lines = raw_report.strip().split("\n")

    if formatting_style == "compact":
        # Remove extra blank lines
        formatted_lines = []
        prev_blank = False
        for line in lines:
            if not line.strip():
                if not prev_blank:
                    formatted_lines.append("")
                prev_blank = True
            else:
                formatted_lines.append(line)
                prev_blank = False
        return "\n".join(formatted_lines)

    elif formatting_style == "detailed":
        # Add separator lines between sections
        formatted_lines = []
        for line in lines:
            formatted_lines.append(line)
            # Add separator after header-like lines
            stripped = line.strip()
            if stripped and stripped.isupper() and len(stripped) > 3:
                formatted_lines.append("─" * 60)
        return "\n".join(formatted_lines)

    else:
        # Standard formatting — clean up whitespace
        return "\n".join(line.rstrip() for line in lines)


def extract_key_findings(report_text: str) -> List[str]:
    """Extract key findings and important items from a report.

    Looks for lines that indicate findings, diagnoses, or action items.

    Args:
        report_text: The full report text.

    Returns:
        List of key finding strings.
    """
    if not report_text:
        return []

    findings: List[str] = []
    keywords = [
        "diagnosis", "finding", "impression", "assessment",
        "recommendation", "plan", "follow-up", "medication",
        "procedure", "result", "conclusion",
    ]

    for line in report_text.split("\n"):
        stripped = line.strip().lower()
        if not stripped:
            continue
        # Lines starting with bullet points or numbers
        if stripped.startswith(("-", "•", "*")) or (
            len(stripped) > 2 and stripped[0].isdigit() and stripped[1] in ".)"
        ):
            findings.append(line.strip())
        # Lines containing key medical terms
        elif any(kw in stripped for kw in keywords):
            findings.append(line.strip())

    return findings


# ---------------------------------------------------------------------------
# Report session tracker
# ---------------------------------------------------------------------------

class ReportSession:
    """Track generated reports across a session."""

    def __init__(self) -> None:
        """Initialize the report session."""
        self.reports: List[Dict[str, Any]] = []

    def add_report(
        self,
        report_type: str,
        clinical_data: str,
        generated_report: str,
    ) -> None:
        """Add a generated report to the session.

        Args:
            report_type: Type of report generated.
            clinical_data: Input clinical data.
            generated_report: The generated report text.
        """
        entry = {
            "timestamp": datetime.now().isoformat(),
            "report_type": report_type,
            "clinical_data": clinical_data,
            "generated_report": generated_report,
        }
        self.reports.append(entry)
        logger.info("Added report to session (total: %d)", len(self.reports))

    def get_reports(self) -> List[Dict[str, Any]]:
        """Get all reports in this session.

        Returns:
            Copy of the reports list.
        """
        return list(self.reports)

    def get_summary(self) -> Dict[str, Any]:
        """Get a summary of the session.

        Returns:
            Dictionary with session statistics.
        """
        if not self.reports:
            return {
                "total_reports": 0,
                "report_types": [],
                "all_types": [],
            }

        all_types: List[str] = []
        for entry in self.reports:
            rt = entry["report_type"]
            if rt not in all_types:
                all_types.append(rt)

        return {
            "total_reports": len(self.reports),
            "report_types": all_types,
            "all_types": all_types,
        }


# ---------------------------------------------------------------------------
# Display helpers
# ---------------------------------------------------------------------------

def display_disclaimer() -> None:
    """Display the medical disclaimer using rich formatting."""
    from rich.console import Console
    from rich.panel import Panel

    console = Console()
    console.print(Panel(DISCLAIMER, title="⚕️  Physician Review Required", border_style="red"))
