"""
Medical Report Writer - Streamlit Web UI

A browser-based interface for generating medical reports, discharge summaries,
and referral letters using a local LLM.

⚠️ DISCLAIMER: All generated reports MUST be reviewed by a licensed physician.
"""

import sys
import os

# Path setup for common module
_common_path = os.path.join(os.path.dirname(__file__), '..', '..', '..')
sys.path.insert(0, os.path.abspath(_common_path))

try:
    import streamlit as st
except ImportError:
    print("ERROR: Streamlit is not installed. Install it with: pip install streamlit")
    print("Then run: streamlit run src/medical_report_writer/web_ui.py")
    sys.exit(1)

from medical_report_writer.core import (
    DISCLAIMER,
    REPORT_TYPES,
    generate_report,
    generate_discharge_summary,
    generate_referral_letter,
    format_report,
    extract_key_findings,
    ReportSession,
    check_ollama_running,
)

# Custom CSS for professional dark theme
st.set_page_config(page_title="Medical Report Writer", page_icon="🏥", layout="wide")

st.markdown("""
<style>
    .main { background-color: #0e1117; }
    .stApp { background: linear-gradient(180deg, #0e1117 0%, #1a1a2e 100%); }
    h1 { background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-size: 2.5rem !important; }
    h2 { color: #667eea !important; }
    h3 { color: #a78bfa !important; }
    .stButton>button { background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; border: none; border-radius: 8px; padding: 0.5rem 2rem; font-weight: 600; transition: transform 0.2s; }
    .stButton>button:hover { transform: translateY(-2px); box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4); }
    .stTextInput>div>div>input, .stTextArea>div>div>textarea { background-color: #1a1a2e; border: 1px solid #333; color: #e0e0e0; border-radius: 8px; }
    .stSelectbox>div>div { background-color: #1a1a2e; border: 1px solid #333; }
    .stMetric { background: linear-gradient(135deg, #1a1a2e, #16213e); padding: 1rem; border-radius: 10px; border: 1px solid #333; }
    .css-1d391kg { background-color: #1a1a2e; }
    div[data-testid="stSidebar"] { background: linear-gradient(180deg, #1a1a2e 0%, #16213e 100%); }
    .stSuccess { background-color: rgba(102, 126, 234, 0.1); border: 1px solid #667eea; }
    footer { visibility: hidden; }
    .block-container { padding-top: 2rem; }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------------

if "session" not in st.session_state:
    st.session_state.session = ReportSession()
if "conversation" not in st.session_state:
    st.session_state.conversation = []

# ---------------------------------------------------------------------------
# Top disclaimer banner
# ---------------------------------------------------------------------------

st.error(
    "⚠️ **PHYSICIAN REVIEW REQUIRED** — All reports generated by this tool are "
    "AI-drafted documents that **MUST** be reviewed, verified, and approved by a "
    "licensed physician before clinical use. All data is processed **LOCALLY** — "
    "no patient data leaves this machine (HIPAA-friendly)."
)

st.title("🏥 Medical Report Writer")
st.caption("AI-powered clinical report generation — 100% local, HIPAA-friendly")

# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------

with st.sidebar:
    st.header("⚙️ Settings")

    st.subheader("📋 Report Types")
    for key, info in REPORT_TYPES.items():
        st.write(f"**{info['name']}** — {info['description']}")

    st.divider()

    show_history = st.checkbox("Show session history", value=True)

    st.divider()
    st.subheader("🔒 Privacy Notice")
    st.write(
        "All data is processed **locally** using Ollama. "
        "No patient information is transmitted to any external server."
    )

# ---------------------------------------------------------------------------
# Main area — Tabs
# ---------------------------------------------------------------------------

tab1, tab2, tab3 = st.tabs(["📄 General Report", "🏥 Discharge Summary", "📨 Referral Letter"])

# ---------------------------------------------------------------------------
# Tab 1: General Report
# ---------------------------------------------------------------------------

with tab1:
    st.subheader("📄 Generate Medical Report")

    col1, col2 = st.columns([2, 1])

    with col1:
        report_type = st.selectbox(
            "Report Type",
            options=list(REPORT_TYPES.keys()),
            format_func=lambda k: REPORT_TYPES[k]["name"],
        )

        clinical_data = st.text_area(
            "Clinical Data",
            height=200,
            placeholder="Enter clinical data, observations, test results, etc...",
        )

    with col2:
        st.write("**Patient Demographics** (optional)")
        patient_name = st.text_input("Patient Name", placeholder="e.g., John Doe")
        patient_age = st.text_input("Age / DOB", placeholder="e.g., 45 years")
        patient_gender = st.text_input("Gender", placeholder="e.g., Male")
        patient_mrn = st.text_input("MRN", placeholder="e.g., MRN-12345")

    demographics = None
    if any([patient_name, patient_age, patient_gender, patient_mrn]):
        demo_parts = []
        if patient_name:
            demo_parts.append(f"Name: {patient_name}")
        if patient_age:
            demo_parts.append(f"Age/DOB: {patient_age}")
        if patient_gender:
            demo_parts.append(f"Gender: {patient_gender}")
        if patient_mrn:
            demo_parts.append(f"MRN: {patient_mrn}")
        demographics = "\n".join(demo_parts)

    generate_clicked = st.button(
        "📝 Generate Report", type="primary",
        disabled=not clinical_data.strip(),
        key="gen_report",
    )

    if generate_clicked and clinical_data.strip():
        if not check_ollama_running():
            st.error(
                "❌ **Ollama is not running.** Please start Ollama first with `ollama serve` "
                "and ensure the model is available (`ollama pull gemma4`)."
            )
        else:
            with st.spinner("Generating report with AI..."):
                try:
                    report = generate_report(
                        clinical_data, report_type, demographics,
                        st.session_state.conversation,
                    )
                    st.markdown("### Generated Report")
                    st.markdown(report)

                    st.code(report, language="markdown")

                    st.session_state.conversation.append(
                        {"role": "user", "content": clinical_data}
                    )
                    st.session_state.conversation.append(
                        {"role": "assistant", "content": report}
                    )
                    st.session_state.session.add_report(report_type, clinical_data, report)

                except Exception as exc:
                    st.error(f"❌ Report generation failed: {exc}")

# ---------------------------------------------------------------------------
# Tab 2: Discharge Summary
# ---------------------------------------------------------------------------

with tab2:
    st.subheader("🏥 Generate Discharge Summary")

    admission_data = st.text_area(
        "Admission Data",
        height=120,
        placeholder="Admission date, admitting diagnosis, presenting complaints...",
        key="admission_data",
    )

    hospital_course = st.text_area(
        "Hospital Course",
        height=150,
        placeholder="Description of hospital stay, treatments, procedures performed...",
        key="hospital_course",
    )

    discharge_info = st.text_area(
        "Discharge Information",
        height=120,
        placeholder="Discharge medications, follow-up appointments, patient instructions...",
        key="discharge_info",
    )

    discharge_clicked = st.button(
        "📝 Generate Discharge Summary", type="primary",
        disabled=not all([admission_data.strip(), hospital_course.strip(), discharge_info.strip()]),
        key="gen_discharge",
    )

    if discharge_clicked:
        if not check_ollama_running():
            st.error("❌ **Ollama is not running.** Start with `ollama serve`.")
        else:
            with st.spinner("Generating discharge summary..."):
                try:
                    summary = generate_discharge_summary(
                        admission_data, hospital_course, discharge_info,
                    )
                    st.markdown("### Discharge Summary")
                    st.markdown(summary)
                    st.code(summary, language="markdown")

                    st.session_state.session.add_report(
                        "discharge_summary", admission_data, summary,
                    )
                except Exception as exc:
                    st.error(f"❌ Generation failed: {exc}")

# ---------------------------------------------------------------------------
# Tab 3: Referral Letter
# ---------------------------------------------------------------------------

with tab3:
    st.subheader("📨 Generate Referral Letter")

    ref_patient = st.text_area(
        "Patient Information",
        height=100,
        placeholder="Patient demographics, relevant history...",
        key="ref_patient",
    )

    ref_reason = st.text_area(
        "Reason for Referral",
        height=80,
        placeholder="Why is this patient being referred?",
        key="ref_reason",
    )

    ref_findings = st.text_area(
        "Clinical Findings",
        height=120,
        placeholder="Relevant clinical findings, test results, imaging...",
        key="ref_findings",
    )

    ref_physician = st.text_input(
        "Requesting Physician",
        placeholder="Dr. Smith",
        key="ref_physician",
    )

    referral_clicked = st.button(
        "📝 Generate Referral Letter", type="primary",
        disabled=not all([ref_patient.strip(), ref_reason.strip(), ref_findings.strip()]),
        key="gen_referral",
    )

    if referral_clicked:
        if not check_ollama_running():
            st.error("❌ **Ollama is not running.** Start with `ollama serve`.")
        else:
            with st.spinner("Generating referral letter..."):
                try:
                    letter = generate_referral_letter(
                        ref_patient, ref_reason, ref_findings,
                        ref_physician if ref_physician.strip() else None,
                    )
                    st.markdown("### Referral Letter")
                    st.markdown(letter)
                    st.code(letter, language="markdown")

                    st.session_state.session.add_report(
                        "referral_letter", ref_patient, letter,
                    )
                except Exception as exc:
                    st.error(f"❌ Generation failed: {exc}")

# ---------------------------------------------------------------------------
# Session History
# ---------------------------------------------------------------------------

if show_history:
    reports = st.session_state.session.get_reports()
    if reports:
        st.divider()
        st.subheader("📋 Session History")
        for i, entry in enumerate(reversed(reports), 1):
            report_name = REPORT_TYPES.get(
                entry["report_type"], {}
            ).get("name", entry["report_type"])
            with st.expander(
                f"Report #{len(reports) - i + 1} — {report_name} — "
                f"{entry['timestamp'][:19]}"
            ):
                st.write(f"**Type:** {report_name}")
                st.write(f"**Time:** {entry['timestamp'][:19]}")
                st.markdown(entry["generated_report"])

# ---------------------------------------------------------------------------
# Bottom disclaimer banner
# ---------------------------------------------------------------------------

st.divider()
st.warning(
    "⚠️ **REMINDER** — All reports generated by this tool are AI-drafted and "
    "**MUST be reviewed and approved by a licensed physician** before clinical use. "
    "All data is processed locally — no patient information leaves this machine."
)

st.caption("Part of the 90 Local LLM Projects collection • Powered by Ollama • 100% HIPAA-friendly")
